export const dummy_data = [
  {
    id: 1,
    title: 'Yeezy Boost 350 V2 Beluga',
    brand: 'Yeezy',
    model: 'V2 Beluga',
    price: 315,
    image: 'https://i.ibb.co/nkWzsFy/adidas-yeezy-350-beluga.png',
    rates: 1,
    numReviews: 1,
    color: ['grey', 'orange'],
    inStock: true,
    size: [7.5, 8, 9, 9.5, 11],
  },
  {
    id: 2,
    title: 'Jordan 1 Low Fragment x Travis Scott',
    brand: 'Jordan',
    model: 'Fragment',
    price: 999,
    image:
      'https://i.postimg.cc/zXWNnV2k/nike-jordan-1-travis-fragment-low.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'blue', 'black'],
    inStock: true,
    size: [7, 9],
  },
  {
    id: 3,
    title: 'Yeezy Boost 350 V2 Black Red',
    brand: 'Yeezy',
    model: '350 V2 Black Red',
    price: 416,
    image: 'https://i.ibb.co/ggShV9Y/adidas-yeezy-350-bred.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'red'],
    inStock: true,
    size: [5, 6.5, 7, 8, 8.5, 9, 10, 12],
  },
  {
    id: 4,
    title: 'Yeezy Boost 350 V2 Zebra',
    brand: 'Yeezy',
    model: '350 V2 Zebra',
    price: 275,
    image: 'https://i.postimg.cc/nhZyBTDH/adidas-yeezy-350-zebra.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white'],
    inStock: true,
    size: [4, 4.5, 5.5, 6, 7.5, 8, 9, 9.5, 10, 12],
  },
  {
    id: 5,
    title: 'Yeezy Boost 700 V2 Inertia',
    brand: 'Yeezy',
    model: '700 V2 Inertia',
    price: 400,
    image: 'https://i.ibb.co/t2w8nfM/adidas-yeezy-700-inertia.png',
    rates: 1,
    numReviews: 1,
    color: ['blue', 'grey'],
    inStock: true,
    size: [5, 5.5, 7, 7.5, 9],
  },
  {
    id: 6,
    title: 'Yeezy Slide Core',
    brand: 'Yeezy',
    model: 'Slides Core',
    price: 211,
    image: 'https://i.ibb.co/9Wc6zVR/adidas-yeezy-slides-core.png',
    rates: 1,
    numReviews: 1,
    color: ['saddlebrown'],
    inStock: true,
    size: [3, 3.5, 6.5, 8, 8.5],
  },
  {
    id: 7,
    title: 'Nike Dunk Low Panda',
    brand: 'Dunk',
    model: 'Panda',
    price: 232,
    image: 'https://i.ibb.co/7SBt6ty/nike-dunk-low-panda.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white'],
    inStock: true,
    size: [6, 6.5, 7, 7.5, 8, 9, 10, 11, 11.5],
  },
  {
    id: 8,
    title: 'Jordan 1 Low Starfish',
    brand: 'Jordan',
    model: 'Starfish',
    price: 278,
    image: 'https://i.postimg.cc/zBL68c9k/nike-joran-1-low-starfish.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'orange'],
    inStock: true,
    size: [7.5, 8, 9, 10, 11, 11.5],
  },
  {
    id: 9,
    title: 'Jordan 1 Mid Chicago Black Toe',
    brand: 'Jordan',
    model: 'Chicago Black Toe',
    price: 135,
    image: 'https://i.ibb.co/kqM3rC7/nike-jordan-1-mid-chicago-black-toe.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'red', 'white'],
    inStock: true,
    size: [3, 3.5, 5, 5.5, 7, 8.5, 11.5],
  },
  {
    id: 10,
    title: 'Jordan 1 High UNC Chicago',
    brand: 'Jordan',
    model: 'Fearless UNC Chicago',
    price: 414,
    image: 'https://i.ibb.co/PQfWdQV/nike-jordan-1-unc-to-chicago.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'blue', 'red'],
    inStock: true,
    size: [10, 11, 11.5],
  },
  {
    id: 11,
    title: 'Nike Dunk Low Off-White Lot 45',
    brand: 'Dunk',
    model: 'Off-White Lot 45',
    price: 710,
    image: 'https://i.ibb.co/DPF3btT/nike-off-white-dunk-low-lot-45.png',
    rates: 1,
    numReviews: 1,
    color: ['pink', 'grey', 'white'],
    inStock: true,
    size: [8, 11],
  },
  {
    id: 12,
    title: 'Puma RS-X Core',
    brand: 'Puma',
    model: 'Sci-Fi White',
    price: 112,
    image: 'https://i.ibb.co/zGhXbWF/puma-rs-x-core.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white'],
    inStock: true,
    size: [4, 4.5, 6, 6.5, 8, 9.5],
  },
  {
    id: 13,
    title: 'Yeezy Boost 350 V2 Natural',
    brand: 'Yeezy',
    model: 'V2 Natural',
    price: 258,
    image: 'https://i.ibb.co/cyBNzgH/adidas-yeezy-350-natural.png',
    rates: 1,
    numReviews: 1,
    color: ['white'],
    inStock: true,
    size: [4, 5, 6, 7, 7.5, 9, 12],
  },
  {
    id: 14,
    title: 'Yeezy Boost 350 V2',
    brand: 'Yeezy',
    model: 'MX Oat',
    price: 225,
    image: 'https://i.ibb.co/r5G31PF/adidas-yeezy-350-OAT.png',
    rates: 1,
    numReviews: 1,
    color: ['yellow', 'orange', 'blue'],
    inStock: true,
    size: [8, 8.5, 10, 10.5, 11],
  },
  {
    id: 15,
    title: 'Yeezy Boost 350 V2 Oreo',
    brand: 'Yeezy',
    model: 'Coral Black White',
    price: 321,
    image: 'https://i.ibb.co/18Jd8P5/adidas-yeezy-350-oreo.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white'],
    inStock: true,
    size: [5, 5.5, 8, 9, 9.5],
  },
  {
    id: 16,
    title: 'Yeezy 450 Cloud White',
    brand: 'Yeezy',
    model: 'Cloud White',
    price: 278,
    image: 'https://i.ibb.co/vxvcv0V/adidas-yeezy-450-cloud-white.png',
    rates: 1,
    numReviews: 1,
    color: ['white'],
    inStock: true,
    size: [4, 4.5, 5.5, 6, 7.5, 8, 9, 9.5, 10, 12],
  },
  {
    id: 17,
    title: 'Yeezy 450 Dark Slate',
    brand: 'Yeezy',
    model: 'Dark Slate',
    price: 272,
    image: 'https://i.ibb.co/xXwwFSy/adidas-yeezy-450-dark-slate.png',
    rates: 1,
    numReviews: 1,
    color: ['black'],
    inStock: true,
    size: [4, 4.5, 5.5, 6, 7.5, 8, 9, 9.5, 10, 12],
  },
  {
    id: 18,
    title: 'Yeezy Boost 700 V2 Geode',
    brand: 'Yeezy',
    model: 'Geode',
    price: 291,
    image: 'https://i.ibb.co/c2vJVbB/adidas-yeezy-700-geode.png',
    rates: 1,
    numReviews: 1,
    color: ['saddlebrown', 'grey'],
    inStock: true,
    size: [3, 3.5, 6.5, 8, 8.5],
  },
  {
    id: 19,
    title: 'Yeezy Boost 700 Wave Runner',
    brand: 'Yeezy',
    model: 'Wave Runner',
    price: 344,
    image: 'https://i.ibb.co/1mdcmDW/adidas-yeezy-700-wave-runner.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white', 'grey'],
    inStock: true,
    size: [6, 6.5, 7, 7.5, 8, 9, 10, 11, 11.5, 12],
  },
  {
    id: 20,
    title: 'Yeezy Slide Bone',
    brand: 'Yeezy',
    model: 'Slide Bone',
    price: 322,
    image: 'https://i.ibb.co/QKyQWXR/adidas-yeezy-slides-bone.png',
    rates: 1,
    numReviews: 1,
    color: ['white'],
    inStock: true,
    size: [3, 9, 10, 11, 11.5],
  },
  {
    id: 21,
    title: 'Yeezy Slide Pure',
    brand: 'Yeezy',
    model: 'Slide Pure',
    price: 181,
    image: 'https://i.ibb.co/zmm6nqz/adidas-yeezy-slides-pure.png',
    rates: 1,
    numReviews: 1,
    color: ['saddlebrown'],
    inStock: true,
    size: [3, 3.5, 5, 5.5, 7, 8.5, 11.5],
  },
  {
    id: 22,
    title: 'Jordan 1 Low SB UNC',
    brand: 'Jordan',
    model: 'UNC',
    price: 529,
    image: 'https://i.ibb.co/gSqCd2x/nike-joran-1-low-unc.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'blue'],
    inStock: true,
    size: [3, 3.5, 6, 6.5, 8, 8.5, 9, 11, 12],
  },
  {
    id: 23,
    title: 'Jordan 1 Low Wolf Grey',
    brand: 'Jordan',
    model: 'Wolf Grey',
    price: 304,
    image: 'https://i.ibb.co/7JtKg0z/nike-joran-1-low-wolf-grey.png',
    rates: 1,
    numReviews: 1,
    color: ['grey', 'white'],
    inStock: true,
    size: [3, 3.5, 5.5, 6, 6.5, 7, 8, 11, 12],
  },
  {
    id: 24,
    title: 'Jordan 1 Retro High x Travis Scott',
    brand: 'Jordan',
    model: 'Travis Scott',
    price: 999,
    image: 'https://i.ibb.co/2W5gXNT/nike-jordan-1-travis-mocha-high.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white', 'saddlebrown'],
    inStock: true,
    size: [8, 9, 11, 12, 10.5],
  },
  {
    id: 25,
    title: 'Jordan 1 Retro Low OG SP x Travis Scott',
    brand: 'Jordan',
    model: 'Travis Scott ',
    price: 999,
    image: 'https://i.ibb.co/nQnCRJ6/nike-jordan-1-travis-mocha-low.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'white', 'saddlebrown'],
    inStock: true,
    size: [3.5, 6, 6.5, 7, 7.5, 10.5],
  },
  {
    id: 26,
    title: 'Jordan 4 Retro UNC',
    brand: 'Jordan',
    model: 'University Blue',
    price: 429,
    image: 'https://i.ibb.co/kJH3HD8/nike-jordan-4-university-blue.png',
    rates: 1,
    numReviews: 1,
    color: ['black', 'blue', 'grey'],
    inStock: true,
    size: [4, 4.5, 5.5, 6, 6.5, 8, 9.5, 10.5],
  },
  {
    id: 27,
    title: 'Puma RS-Dreamer',
    brand: 'Puma',
    model: 'J.Cole Purple Heart',
    price: 101,
    image: 'https://i.ibb.co/hK4V4mH/puma-rs-dreamer-purple.png',
    rates: 1,
    numReviews: 1,
    color: ['yellow', 'purple', 'black'],
    inStock: true,
    size: [6, 6.5, 8, 9.5],
  },
  {
    id: 28,
    title: 'Nike SB Dunk Low',
    brand: 'Dunk',
    model: 'StrangeLove Skateboards',
    price: 999,
    image: 'https://i.ibb.co/jMMW6rX/nike-sb-dunk-strange-Love.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'red', 'pink'],
    inStock: true,
    size: [3.5, 4.5, 5.5, 11.5],
  },
  {
    id: 29,
    title: 'Nike Dunk Low UNC',
    brand: 'Dunk',
    model: 'UNC',
    price: 348,
    image: 'https://i.ibb.co/SKVRntS/nike-dunk-low-unc.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'blue'],
    inStock: true,
    size: [8, 8.5, 9, 9.5, 10, 10.5],
  },
  {
    id: 30,
    title: 'Nike Dunk Low Michigan',
    brand: 'Dunk',
    model: 'Michigan State',
    price: 361,
    image: 'https://i.ibb.co/Z8S67fz/nike-dunk-low-michigan.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'green'],
    inStock: true,
    size: [3, 3.5, 6, 6.5, 8, 8.5, 9, 11, 12],
  },
  {
    id: 31,
    title: 'Nike SB Dunk Low',
    brand: 'Dunk',
    model: 'Michigan State',
    price: 526,
    image: 'https://i.ibb.co/VxB80fj/nike-dunk-low-chicago.png',
    rates: 1,
    numReviews: 1,
    color: ['white', 'black', 'red'],
    inStock: true,
    size: [3, 3.5, 6, 6.5],
  },
];
